apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: spring
  janus-idp.io/tekton: spring
  backstage.io/kubernetes-id: spring
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spring
resources:
- deployment.yaml
- route.yaml
- service.yaml
