apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: spring
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring 
  name: spring
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spring
    weight: 100 
